### PR TITLE
Make page.image url relative to site rather than absolute

### LINKED ISSUE #24: site.logo is relative while page.image is absolute
Is it necessary to make page.image an absolute URL instead of relative? It would be much nicer to make it relative like site.logo. Thanks for a nice gem!

### PR DESCRIPTION
**Pull request by boturnbow**
Fixes #24 

Tests pass when https://github.com/benbalter/jekyll-seo-tag/pull/43 is merged,

### CODE REVIEW

**Comment by benbalter** [comment]
Thanks @boturnbow! I believe the failing tests are unrelated and due to https://github.com/benbalter/jekyll-seo-tag/pull/43.

**Comment by boturnbow** [comment]
Thanks to @pathawks for answering my question about the failing tests. This was my first pull request for a public project - yall made it easy.

**Comment by pathawks** [comment]
:tada: Cool!

Thanks for contributing :+1:

**Comment by bkeepers** [comment]
@boturnbow :confetti_ball: :star2: Congrats on your first merged pull request! May this be the beginning of a wonderful adventure.

**Pull request merged**
